name: 'Setup Node.js and pnpm'
description: 'Sets up Node.js and pnpm with caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  enable-corepack:
    description: 'Enable corepack'
    required: false
    default: 'false'
    cwd:
      description: "Changes node's process.cwd() if the project is not located on the root. Default to process.cwd()"
      required: false
      default: '.'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      # Pinned to v4 commit hash for security
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: ⚙️ Enable Corepack
      if: ${{ inputs.enable-corepack == 'true' }}
      shell: bash
      working-directory: ${{ inputs.cwd }}
      run: |
          corepack enable
          echo "corepack enabled"

    - uses: pnpm/action-setup@7088e561eb65bb68695d245aa206f005ef30921d # v4.1.0
      if: ${{ inputs.enable-corepack == 'false' }}
      with:
        run_install: false
        # If you're not setting the packageManager field in package.json, add the version here
        # version: 10.13.1

    - name: Expose pnpm config(s) through "$GITHUB_OUTPUT"
      id: pnpm-config
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Cache rotation keys
      id: cache-rotation
      shell: bash
      run: |
        echo "YEAR_MONTH=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-config.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-cache-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-

    # Prevent store to grow over time (not needed with yarn)
    # Note: not perfect as it prune too much in monorepos so the idea
    #       is to use cache-rotation as above. In the future this might work better.
    - name: Prune pnpm store
      shell: bash
      run: pnpm prune store

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.cwd }}
      run: pnpm install --frozen-lockfile --prefer-offline
      env:
        # Other environment variables
        HUSKY: '0' # By default do not run HUSKY install

    - name: Verify installation
      shell: bash
      run: |
        echo "Checking Node.js installation"
        node --version
        echo "Checking pnpm installation"
        pnpm --version
