reviewers:
  defaults:
    - team:astrum

  groups:
    astrum:
      - team:astrum

files:
  '**':
    - team:astrum

options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
    - WIP
    - DRAFT
    - NO REVIEW
    - SKIP REVIEW
  enable_group_assignment: false
