name: 'Docker Build and Push'
description: 'Builds and pushes a Docker image to GitHub Container Registry'

inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true
  dockerfile:
    description: 'Path to the Dockerfile'
    required: true
  context:
    description: 'Build context'
    required: false
    default: '.'
  github-token:
    description: 'GitHub token for authentication'
    required: true
  build-args:
    description: 'Build arguments for Docker build'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/${{ inputs.image-name }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=sha,format=long

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ inputs.build-args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
