#!/usr/bin/env bash

set -e

# Ensure docs directory exists
mkdir -p docs

# Output file
doc_file="docs/structure.md"

# Timestamp
timestamp="$(date '+%Y-%m-%d %H:%M:%S')"

cat > "$doc_file" <<EOF
# Project Structure

_Auto-generated by scripts/generate-structure-docs.sh on ${timestamp}_

> **Note:** This structure is automatically generated. Do not edit this file manually.

\`\`\`plaintext
EOF

# Run tree-extended with npx, fail if not available
if ! npx --yes tree-extended \
  -max=5 \
  -max-show-not-empty \
  -gitignore \
  -ignore node_modules,build,.git,public,dist,coverage,.DS_Store,.idea,.vscode,*.log,*.tmp,*.cache \
  --no-color \
  >> "$doc_file"; then
  echo >&2 "Error: tree-extended could not be run with npx. Please check your network connection or try 'pnpm add -D tree-extended' to install it locally."
  exit 1
fi

echo '```' >> "$doc_file"
echo "Project structure documentation generated at $doc_file"
