#!/usr/bin/env bash

set -e

# Ensure docs directory exists
mkdir -p docs

# Output file
doc_file="docs/structure.md"

# Timestamp
timestamp="$(date '+%Y-%m-%d %H:%M:%S')"

cat > "$doc_file" <<EOF
# Project Structure

_Auto-generated by scripts/generate-structure-docs.sh on ${timestamp}_

> **Note:** This structure is automatically generated. Do not edit this file manually.

\`\`\`plaintext
EOF

# Check if tree-extended is available in node_modules
if ! npx --no-install tree-extended --version &> /dev/null; then
  echo "tree-extended not found in node_modules, installing with pnpm..."
  if ! pnpm add -Dw tree-extended; then
    echo >&2 "Error: Failed to install tree-extended. Please check your network connection or install it manually with 'pnpm add -Dw tree-extended'."
    exit 1
  fi
fi

# Run tree-extended from node_modules
if ! npx tree-extended \
  -max=5 \
  -max-show-not-empty \
  -gitignore \
  -ignore node_modules,build,.git,public,dist,coverage,.DS_Store,.idea,.vscode,*.log,*.tmp,*.cache \
  --no-color \
  >> "$doc_file"; then
  echo >&2 "Error: Failed to run tree-extended. Please check the installation."
  exit 1
fi

echo '```' >> "$doc_file"
echo "Project structure documentation generated at $doc_file"
