#!/usr/bin/env bash

set -e

# Ensure docs directory exists
mkdir -p docs

# Output file
doc_file="docs/structure.md"

# Timestamp
timestamp="$(date '+%Y-%m-%d %H:%M:%S')"

cat > "$doc_file" <<EOF
# Project Structure

**Auto-generated by scripts/generate-structure-docs.sh on ${timestamp}**

> **Note:** This structure is automatically generated. Do not edit this file manually.

## Root Directory Overview

\`\`\`plaintext
EOF

# Check if tree-extended is available in node_modules
if ! npx --no-install tree-extended --version &> /dev/null; then
  echo "tree-extended not found in node_modules, installing with pnpm..."
  if ! pnpm add -Dw tree-extended; then
    echo >&2 "Error: Failed to install tree-extended. Please check your network connection or install it manually with 'pnpm add -Dw tree-extended'."
    exit 1
  fi
fi

# Run tree-extended from node_modules with more focused output
if ! npx tree-extended \
  -max=2 \
  -max-show-not-empty \
  -gitignore \
  -ignore "node_modules,build,dist,.vite*,.bin,tmp,.artifact,*.jar,*.class,.DS_Store,.gitignore,.env*,*.compiler.options,coverage,.git,public,.idea,.vscode,*.log,*.tmp,*.cache,target,out,generated,bin,lib,logs,temp,assets/generated,__pycache__,*.pyc,*.pyo,*.pyd,*.so,*.dylib,*.dll,*.exe,*.o,*.a,*.obj,*.zip,*.tar,*.gz,*.rar,*.7z,.github,workflows,config,gradle,.DS_Store" \
  --no-color \
  >> "$doc_file"; then
  echo >&2 "Error: Failed to run tree-extended. Please check the installation."
  exit 1
fi

# Add a note about the simplified structure
cat >> "$doc_file" <<EOF

## Detailed Structure

## Backend Structure (\`server/\`)

\`\`\`plaintext
server/
└── thryve/                 # Main Spring Boot application
    ├── src/main/kotlin/    # Kotlin source code
    ├── src/main/resources/ # Configuration files, migrations
    └── src/test/kotlin/    # Test source code
\`\`\`

## Frontend Structure (\`client/\`)

\`\`\`plaintext
client/
├── apps/
│   ├── web/               # Main Vue.js application
│   └── landing-page/      # Astro marketing site
├── packages/
│   ├── utilities/         # Shared utility functions
│   └── tsconfig/         # Shared TypeScript configs
└── config/               # Shared build configurations
\`\`\`

## Shared Libraries (\`shared/\`)

\`\`\`plaintext
shared/
├── common/                # Common utilities (Kotlin)
└── spring-boot-common/    # Spring Boot shared components
\`\`\`

## Infrastructure (\`infra/\`)

\`\`\`plaintext
infra/
├── keycloak/             # Keycloak configuration
├── postgresql/           # Database setup and init scripts
└── ssl/                  # Local SSL certificates
\`\`\`

## Documentation (\`docs/\`)

\`\`\`plaintext
docs/
├── conventions/          # Development guidelines
├── authentication/       # Auth documentation
├── frontend/            # Frontend-specific docs
└── landing/             # Landing page assets
\`\`\`
EOF

echo '```' >> "$doc_file"
echo "Project structure documentation generated at $doc_file"
