server:
  port: 8080
  # make sure requests the proxy uri instead of the server one
  forward-headers-strategy: native
logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    com.hatchgrid: DEBUG
spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true
  liquibase:
    contexts: dev
springdoc:
  show-actuator: true
