-- All DDL statements from this file have been migrated to Liquibase changelogs
-- (see server/thryve/src/main/resources/db/changelog/).
-- This file is intentionally left almost empty to avoid conflicts.
