name: Markdown Lint

on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.mdx"

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 🧩 Setup Node.js and pnpm
        uses: ./.github/actions/setup/node
        with:
          node-version: "22"
      - run: pnpm install
      - run: npx markdownlint-cli2 "**/*.md" "**/*.mdx"
