name: Require linked issue

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  check-linked-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Enforce linked issue
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const title = context.payload.pull_request.title || '';
            const body = context.payload.pull_request.body || '';
            const pattern = /(close[sd]?|fix(e[sd])?|resolve[sd]?)\s*#\d+/i;
            if (!pattern.test(title) && !pattern.test(body)) {
              core.setFailed('This PR must be linked to an issue (use "Closes #123").');
            }