name: Ruler Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruler-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install Ruler
        run: npm install -g @intellectronica/ruler
      - name: Check Ruler sync
        run: ruler check
