name: Test PNPM Setup
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  test-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Pinned to v4 commit hash for security
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Restore pnpm cache
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup/node
        with:
          node-version: '22'
          pnpm-version: '10.13.1'

      - name: Test pnpm installation
        run: |
          echo "PATH=$PATH"
          which pnpm || echo "pnpm not found"
          pnpm --version
