name: Test PNPM Setup
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  test-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Pinned to v4 commit hash for security
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js
        # Pinned to v4 commit hash for security
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
        with:
          version: 10.13.1
          run_install: false

      - name: Test pnpm installation
        run: |
          echo "PATH=$PATH"
          which pnpm || echo "pnpm not found"
          pnpm --version
          echo "STORE_PATH=$(pnpm store path)"
